### ISSUE TITLE
Update command line syntax

### ISSUE THREAD

**Issue by deluan** [zfuller/navidrome-role#1]
Hey, thanks for this project, great contribution! 

With new 0.25.0 version, cmd line flags are now POSIX compliant. This means that instead of `-configfile` in the line below, you need to use `--configfile`, or it will :

https://github.com/zfuller/navidrome-role/blob/523d1847a513da8635f7f32313d1e0ca7c2992ef/templates/etc/systemd/system/navidrome.service.j2#L18

or else it will fail with an error like this:
```
$ navidrome -configfile ./navidrome.toml
Error: unknown command "./navidrome.toml" for "navidrome"
Run 'navidrome --help' for usage.
unknown command "./navidrome.toml" for "navidrome"
```

**Comment by zfuller** [comment]
whoops, admittedly I didn't test before upping the version last night! fixed
